# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20160210_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=500)),
                ('sequence_no', models.IntegerField(max_length=3)),
                ('children', models.ManyToManyField(blank=True, null=True, related_name='_list_item_children_+', to='todo.list_item')),
                ('item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.list_item')),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_phone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='todo_list_item',
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
        migrations.AddField(
            model_name='list_item',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.user_profile'),
        ),
    ]
